name = "text-generation-frontend"
compatibility_date = "2024-05-21"
pages_build_output_dir = "out"

[env.production]
NEXT_PUBLIC_API_URL = "https://text-generation-api-production.faceswap.workers.dev"
NEXT_PUBLIC_R2_BUCKET = "text-generation" 