name = "text-generation-chat"
compatibility_date = "2024-01-15"

[build]
command = "npm install && npm run build"
cwd = "frontend"

[build.environment_variables]
NODE_VERSION = "18"

[[pages_build_output_dir]]
dir = "frontend/out" 