[site]
bucket = "./out"
entry-point = "."

[build]
command = "npm run build"
output_dir = "out"

[build.upload]
format = "directory"

[[build.processing.resources]]
paths = ["/_next/static/chunks/*.js"]
content_type = "application/javascript"

[[build.processing.resources]]
paths = ["/_next/static/css/*.css"]
content_type = "text/css"

[env.production]
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"
NEXT_PUBLIC_R2_BUCKET = "text-generation" 