name = "text-generation-chat"
compatibility_date = "2024-01-15"

[build]
command = "./build.sh"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"
NEXT_PUBLIC_R2_BUCKET = "text-generation"

[env.production]
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"

[site]
bucket = "./frontend/out" 