name = "text-generation-api"
main = "cloudflare-api-worker.js"
compatibility_date = "2024-06-15"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "text-generation"

[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "text-generation" 