name = "text-generation-chat"
compatibility_date = "2024-01-15"

# Cloudflare Pages配置
pages_build_output_dir = "frontend/out"

[build]
command = "./build.sh"
cwd = "."

[env.production.vars]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"
NEXT_PUBLIC_R2_BUCKET = "text-generation"

[env.production]
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"

[site]
bucket = "./frontend/out" 