name = "text-generation-chat"
compatibility_date = "2024-01-15"

# Pages 输出目录配置
pages_build_output_dir = "frontend/out"

[env.production.vars]
NODE_VERSION = "18"
NEXT_PUBLIC_API_URL = "https://api-text-generation.runpod.app"
NEXT_PUBLIC_R2_BUCKET = "text-generation" 